Console.WriteLine();
Console.WriteLine("Определяем расстояние между точками в 3D!");
Console.Write("Введите координаты X точки A: ");
int xA = int.Parse(Console.ReadLine()!);
Console.WriteLine();
Console.Write("Введите координаты Y точки A: ");
int yA = int.Parse(Console.ReadLine()!);
Console.WriteLine();
Console.Write("Введите координаты Z точки A: ");
int zA = int.Parse(Console.ReadLine()!);
Console.WriteLine();
Console.Write("Введите координаты X точки B: ");
int xB = int.Parse(Console.ReadLine()!);
Console.WriteLine();
Console.Write("Введите координаты Y точки B: ");
int yB = int.Parse(Console.ReadLine()!);
Console.WriteLine();
Console.Write("Введите координаты Z точки B: ");
int zB = int.Parse(Console.ReadLine()!);

int xAB = (xB - xA);
int yAB = (yB - yA);
int zAB = (zB - zA);
xAB = xAB * xAB;
yAB = yAB * yAB;
zAB = zAB * zAB;
int distTemp = xAB + yAB + zAB;
double dist = Math.Sqrt(distTemp);
Console.WriteLine();
Console.WriteLine("Расстояние между точками А и B в трёхмерном пространстве равно " + dist);
Console.WriteLine();